@baseUrl="http://localhost:8002/v1"

### User Registration
POST http://localhost:8002/v1/user/register
Content-Type: application/json

{
    "email" : "phuocsanhst@gmail.com",
    "purpose" : "test"
}