version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecommerce_sq
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: GO_ECOMMERCE
      MYSQL_USER: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0
    container_name: redis_ecommerce_sq
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
