server:
  port: 8082
  mode: dev
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: GO_ECOMMERCE
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500 # megabytes
  max_backups: 3
  max_age: 28 # days
  compress: true
