server:
  port: 8082
  mode: dev
mysql:
  host: mysql_ecommerce_sq
  port: 3306
  username: root
  password: 123456
  dbname: GO_ECOMMERCE
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

redis:
  host: redis_ecommerce_sq # 127.0.0.1
  port: 6379
  password: # no pw set
  db: 0 # use default db
  pool_size: 10 # max connect to redis

logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500 # megabytes
  max_backups: 3
  max_age: 28 # days
  compress: true
