server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  database: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name:
